from pathlib import Path

path = Path("src/main/main.cpp")
text = path.read_text(encoding="utf-8")

old_workers = '''    std::thread t0;\n    std::thread t1;\n    std::thread t2;\n    if (using_threading) {\n        // Create worker threads.\n        std::cout << "Using " << threads << " threads (" << render_threads << " renderer threads)" << std::endl;\n        if (prepare_threads) {\n            // prepare_thread produces the S16 output - road, sky, sprites etc\n            // Note - this thread also launches the sound callback, so don't pin this thread to one core.\n            t0 = std::thread(prepare_thread);\n        }\n        // render_threads process with S16 output with Blargg filter, if enabled,\n        // or convert the S16 palette-based output to RGB otherwise\n        t1 = std::thread(render_thread,render_threads,0);\n        // pin_thread_to_core(t1,2);\n        if (render_threads == 2) {\n            t2 = std::thread(render_thread,render_threads,1);\n            // pin_thread_to_core(t2,3);\n        }\n    }\n'''

new_workers = '''    std::thread t0;\n    std::thread t1;\n    std::thread t2;\n\n    // Resolution changes rebuild the complete SDL/GL renderer and its CPU\n    // surfaces. Keep that critical section completely free of worker threads:\n    // merely waiting for the current jobs is not enough, because otherwise the\n    // workers remain alive against renderer-owned state while it is destroyed.\n    auto start_video_workers = [&]()\n    {\n        if (!using_threading)\n            return;\n\n        running.store(true, std::memory_order_release);\n        if (prepare_threads)\n            t0 = std::thread(prepare_thread);\n\n        t1 = std::thread(render_thread, render_threads, 0);\n        if (render_threads == 2)\n            t2 = std::thread(render_thread, render_threads, 1);\n    };\n\n    auto stop_video_workers = [&]()\n    {\n        if (!using_threading)\n            return;\n\n        running.store(false, std::memory_order_release);\n\n        // All normal frame jobs have already completed before this is called.\n        // These releases only wake the now-idle workers so they can observe the\n        // stop flag and leave their loops.\n        if (prepare_threads && t0.joinable())\n            prepareReady.release();\n        if (t1.joinable())\n            renderReady0.release();\n        if (render_threads == 2 && t2.joinable())\n            renderReady1.release();\n\n        if (t0.joinable()) t0.join();\n        if (t1.joinable()) t1.join();\n        if (t2.joinable()) t2.join();\n    };\n\n    if (using_threading)\n    {\n        std::cout << "Using " << threads << " threads ("\n                  << render_threads << " renderer threads)" << std::endl;\n        start_video_workers();\n    }\n'''

if new_workers not in text:
    if old_workers not in text:
        raise SystemExit("worker startup block not found")
    text = text.replace(old_workers, new_workers, 1)

old_restart = '''        // Check to see if anything happened needing a video restart\n        if (config.videoRestartRequired) {\n            const int previous_hires = config.video.hires;\n            video.disable();\n            config.video.hires = config.video.hires_next;\n            if (!video.init(&roms, &config.video, true))\n            {\n                std::cerr << "Video restart failed; restoring the previous engine resolution.\\n";\n                config.video.hires = previous_hires;\n                config.video.hires_next = previous_hires;\n                if (!video.init(&roms, &config.video, true))\n                {\n                    // Leave the loop before another frame can use missing\n                    // buffers, then join workers and run the normal shutdown.\n                    std::cerr << "Unable to restore video; shutting down.\\n";\n                    cannonball::state = STATE_QUIT;\n                    exit_code = 1;\n                    break;\n                }\n            }\n            video.sprite_layer->set_x_clip(false);\n            config.videoRestartRequired = false;\n            // reset timers as video restart can take a while\n            nextFrameTime = std::chrono::steady_clock::now();\n            vsync = refresh_vsync_state();\n        }\n'''

new_restart = '''        // Check to see if anything happened needing a video restart.\n        if (config.videoRestartRequired) {\n            const int previous_hires = config.video.hires;\n\n            // We are at a frame boundary and have already acquired every\n            // render/prepare completion semaphore above. Fully terminate the\n            // workers as well before freeing renderer-owned memory or GL state.\n            // This makes resolution switching a quiescent operation.\n            stop_video_workers();\n\n            video.disable();\n            config.video.hires = config.video.hires_next;\n            if (!video.init(&roms, &config.video, true))\n            {\n                std::cerr << "Video restart failed; restoring the previous engine resolution.\\n";\n                config.video.hires = previous_hires;\n                config.video.hires_next = previous_hires;\n                if (!video.init(&roms, &config.video, true))\n                {\n                    // Workers are already stopped, so no thread can touch the\n                    // failed renderer while the main loop shuts down.\n                    std::cerr << "Unable to restore video; shutting down.\\n";\n                    config.videoRestartRequired = false;\n                    cannonball::state = STATE_QUIT;\n                    exit_code = 1;\n                    break;\n                }\n            }\n\n            video.sprite_layer->set_x_clip(false);\n            config.videoRestartRequired = false;\n\n            // Only expose the newly-created renderer to workers after every\n            // buffer, surface and GL object is fully initialised.\n            start_video_workers();\n\n            // Reset timers as video restart can take a while.\n            nextFrameTime = std::chrono::steady_clock::now();\n            vsync = refresh_vsync_state();\n        }\n'''

if new_restart not in text:
    if old_restart not in text:
        raise SystemExit("video restart block not found")
    text = text.replace(old_restart, new_restart, 1)

old_shutdown = '''    // Signal the worker threads to quit.\n    if (using_threading) {\n        running.store(false);\n        if (prepare_threads)   { prepareReady.release(); t0.join(); }\n                                 renderReady0.release(); t1.join();\n        if (render_threads==2) { renderReady1.release(); t2.join(); }\n    }\n'''

new_shutdown = '''    // Signal the worker threads to quit. The helper is also safe when a failed\n    // video restart already stopped and joined them.\n    stop_video_workers();\n'''

if new_shutdown not in text:
    if old_shutdown not in text:
        raise SystemExit("worker shutdown block not found")
    text = text.replace(old_shutdown, new_shutdown, 1)

path.write_text(text, encoding="utf-8")
print("Applied quiescent video restart around engine resolution changes")
